User.create(username: "Dungeon Crawler", email: "example@example.com", password: "password")
User.create(username: "Edge Lord", email: "edge@obscure.com", password: "testytest")
User.create(username: "El Capitan", email: "cpt@example.com", password: "1234567890")

Character.create(user_id: 1, name: "Dummy", race: "Test", klass: "Peasant", hp: 100, str: 12, con: 12, dex: 12, int: 12, wis: 12, cha: 12)
Character.create(user_id: 2, name: "Dummy", race: "Test", klass: "Peasant", hp: 100, str: 12, con: 12, dex: 12, int: 12, wis: 12, cha: 12)
Character.create(user_id: 3, name: "Dummy", race: "Test", klass: "Peasant", hp: 100, str: 12, con: 12, dex: 12, int: 12, wis: 12, cha: 12)
Character.create(user_id: 1, name: "Dummy", race: "Test", klass: "Peasant", hp: 100, str: 12, con: 12, dex: 12, int: 12, wis: 12, cha: 12)
Character.create(user_id: 1, name: "Dummy", race: "Test", klass: "Peasant", hp: 100, str: 12, con: 12, dex: 12, int: 12, wis: 12, cha: 12)
Character.create(user_id: 2, name: "Dummy", race: "Test", klass: "Peasant", hp: 100, str: 12, con: 12, dex: 12, int: 12, wis: 12, cha: 12)